name: Charlotteking
favicon: null
layout_spectrum: 0.8985422553960234
typography_spectrum: 0.9468347893562168
title: charlotteking.ca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#252525'
    - '#5b5b5b'
    - '#929292'
    - '#bfbfbf'
  brandStrength: 0.5625
  lightness: 0.31681319000199437
  saturation: 0.09402163699269295
  rhythmicContrast: 0.922097590751946
purpose: []
