typography_spectrum: 0.39606
color:
  brandColors:
    - '#010101'
    - '#252525'
    - '#5b5b5b'
    - '#929292'
    - '#bfbfbf'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.09402163699269295
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75068
analytics:
  google: null
  facebook: null
  twitter: null
name: Charlotteking
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Savannah
    id: ad5a1cce-2eb0-4096-becc-88d45b2b97f9
    type: content
favicon: null
title: charlotteking.ca
purpose: []
