name: Charlotteking
favicon: null
layout_spectrum: 0.50451
typography_spectrum: 0.56047
title: charlotteking.ca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2ff'
    - '#000100'
    - '#a8c9f4'
    - '#777150'
    - '#a0a34d'
  brandStrength: 0.5625
  lightness: 0.31681319000199437
  saturation: 0.09402163699269295
  rhythmicContrast: 0.922097590751946
purpose: []
