name: Charlotteking
favicon: null
layout_spectrum: 0.75068
typography_spectrum: 0.39606
title: charlotteking.ca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#252525'
    - '#5b5b5b'
    - '#929292'
    - '#bfbfbf'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.09402163699269295
  rhythmicContrast: 0.75
purpose: []
